### ISSUE TITLE
Criar arquivo de registro de configuração do projeto

### ISSUE THREAD

**Issue by marcoaraujolsys** [PromoAppSolucoes/promoapp#3]
Criar documento cujo a finalidade será de registrar todos os programas. módulos, variáveis de ambiente, configurações necessárias entre outros para o projeto funcionar fora docker.

Necessário para que seja possível montar separadamente fora de um container.

Facilita o entendimento de um colaborador iniciante sobre as necessidades e dependências do projeto.

**Comment by pgomesdev** [comment]
Documento em desenvolvimento no docs, importarei para o README do git.
