### ISSUE TITLE
Estruturar projeto para multi idioma

### ISSUE THREAD

**Issue by marcoaraujolsys** [PromoAppSolucoes/promoapp#4]
Os projetos WEB e APP deverão atender ao requisito de serem multi idioma.
Desta forma deverá existir um arquivo RESOURCE para cada idioma a ser utilizado.
A utilização do arquivo resource será indicado conforme as coordenadas capturadas automaticamente da requisição solicitante.
Caso ocorra erro na localização, resource padrão será o "pt-br".
Após a criação da sessão, o sistema deverá registrar automaticamente a localização e o resource utilizado para que não seja necessário identificar a localização a cada requisição.

**Comment by pgomesdev** [comment]
O projeto já está com suporte a multi idioma através de serviço. Fechando.
